# Generated by Django 2.0 on 2019-10-21 19:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('update_time', models.DateTimeField(auto_now_add=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=10, unique=True, verbose_name='笔名')),
                ('country', models.CharField(max_length=10, verbose_name='国籍')),
            ],
            options={
                'verbose_name': '作家表',
                'verbose_name_plural': '作家表',
                'db_table': 'author',
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('update_time', models.DateTimeField(auto_now_add=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=20, verbose_name='书名')),
                ('inventory', models.IntegerField(default=0, verbose_name='库存量')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='图书价格')),
                ('image', models.FileField(upload_to='books', verbose_name='图书图片')),
                ('description', models.CharField(max_length=256, verbose_name='图书简介')),
                ('sales', models.IntegerField(default=0, verbose_name='销量')),
                ('details', models.TextField(verbose_name='商品详情')),
                ('status', models.BooleanField(default=True, verbose_name='商品状态')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.Author', verbose_name='作家')),
            ],
            options={
                'verbose_name': '图书表',
                'verbose_name_plural': '图书表',
                'db_table': 'book',
            },
        ),
        migrations.CreateModel(
            name='BookImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('update_time', models.DateTimeField(auto_now_add=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False)),
                ('image', models.ImageField(upload_to='banners', verbose_name='图书路径')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.Book', verbose_name='图书')),
            ],
            options={
                'verbose_name': '图书图片',
                'verbose_name_plural': '图书图片',
                'db_table': 'book_image',
            },
        ),
        migrations.CreateModel(
            name='BookType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('update_time', models.DateTimeField(auto_now_add=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=10, verbose_name='图书类型')),
                ('image', models.ImageField(upload_to='type', verbose_name='类型图片')),
            ],
            options={
                'verbose_name': '图书类别表',
                'verbose_name_plural': '图书类别表',
                'db_table': 'book_type',
            },
        ),
        migrations.CreateModel(
            name='IndexBookImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('update_time', models.DateTimeField(auto_now_add=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False)),
                ('index', models.IntegerField(default=0, verbose_name='播放顺序')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.Book', verbose_name='图书')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.BookImage', verbose_name='图书图片')),
            ],
            options={
                'verbose_name': '首页轮播图',
                'verbose_name_plural': '首页轮播图',
                'db_table': 'index_book_image',
            },
        ),
        migrations.CreateModel(
            name='IndexSaleBanner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('update_time', models.DateTimeField(auto_now_add=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=30, verbose_name='促销活动名称')),
                ('image', models.ImageField(upload_to='banner', verbose_name='活动图片')),
                ('index', models.SmallIntegerField(default=0, verbose_name='展示顺序')),
                ('url', models.URLField(verbose_name='活动链接')),
            ],
            options={
                'verbose_name': '首页促销活动',
                'verbose_name_plural': '首页促销活动',
                'db_table': 'index_sale',
            },
        ),
        migrations.AddField(
            model_name='book',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.BookType', verbose_name='图书类型'),
        ),
    ]
