# Generated by Django 2.0 on 2019-10-21 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='IndexSaleBanner',
            new_name='IndexSaleImage',
        ),
        migrations.AlterField(
            model_name='bookimage',
            name='image',
            field=models.ImageField(upload_to='books', verbose_name='图书路径'),
        ),
        migrations.AlterField(
            model_name='indexbookimage',
            name='image',
            field=models.ImageField(upload_to='banner', verbose_name='图书图片'),
        ),
    ]
