# Generated by Django 2.0 on 2019-10-22 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_auto_20191021_2115'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='unit',
            field=models.CharField(default='本', max_length=5),
        ),
    ]
