# Generated by Django 2.0 on 2019-10-25 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0005_historybook_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historybook',
            name='number',
            field=models.IntegerField(default=1, verbose_name='浏览次数'),
        ),
    ]
