# Generated by Django 2.0 on 2019-10-23 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='tatal',
            new_name='total',
        ),
    ]
