# Generated by Django 2.0 on 2019-10-21 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='icon',
            field=models.ImageField(default='6', upload_to='', verbose_name='用户头像'),
            preserve_default=False,
        ),
    ]
