# Generated by Django 2.0 on 2019-10-21 19:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20191021_1929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraddress',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 21, 19, 40, 50, 488395), verbose_name='添加时间'),
        ),
    ]
