# Generated by Django 2.0 on 2019-10-23 21:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_auto_20191023_1907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraddress',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 23, 21, 46, 56, 27831), verbose_name='添加时间'),
        ),
    ]
