# Generated by Django 2.0 on 2019-10-24 19:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_auto_20191024_1905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraddress',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 24, 19, 18, 41, 583572), verbose_name='添加时间'),
        ),
    ]
