# Generated by Django 2.0 on 2019-10-24 20:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_auto_20191024_1918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraddress',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 24, 20, 45, 20, 705872), verbose_name='添加时间'),
        ),
    ]
