# Generated by Django 2.0 on 2019-10-24 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20191024_1905'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderbooks',
            old_name='goods',
            new_name='books',
        ),
    ]
